### ISSUE TITLE
Secrets check appears not to work

### ISSUE THREAD

**Issue by mtcolman** [bridgecrewio/checkov#1536]
**Describe the bug**
I am trying to see if checkov discovers secrets/passwords in files. I am running `bridgecrew/checkov:2` which is version 2.0.371. I have created 3 files on my local machine and I then mount the directory containing them into the container. I am trying to recreate what has been detailed in this [bridgecrew blog](https://bridgecrew.io/blog/checkov-secrets-scanning-find-exposed-credentials-in-iac/).
```
docker run -it --entrypoint=/bin/bash -v "c/Users/MATTHEWColman/Documents/test/password/":/test bridgecrew/checkov:2
```

I am running the container as root as I haven't specified an alternative user in the run command:
```
id
uid=0(root) gid=0(root) groups=0(root)
```

Within the container I can see the files exist:
```
ls -la /test
total 4
drwxrwxrwx    1 root     root          4096 Aug 25 16:35 .
drwxr-xr-x    1 root     root          4096 Aug 25 16:52 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            44 Aug 25 16:34 providers.tf
-rwxrwxrwx    1 root     root            30 Aug 25 16:35 secret_password.yaml
```

I can view the file contents:
```
bash-5.1# cd test
bash-5.1# cat password.txt
password: mypassword
b64password: bXlwYXNzd29yZAo=
mypassword=secretkey

bash-5.1# cat providers.tf
access_key = "sfffglfgjldfjdlrt5454002lfofd"bash-5.1#

bash-5.1# cat secret_password.yaml
pwd: correcthorsebatterystaple
```

But when I run checkov, I get no results.
```
bash-5.1# pwd
/test

bash-5.1# checkov -f secret_password.yaml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.371

bash-5.1#
```

I've even tried copying the files into the container filesystem at `/newtest` and then running the `checkov` command:
```
bash-5.1# mkdir /newtest
bash-5.1# cp /test/secret_password.yaml /newtest/secret_password.yaml

bash-5.1# ls -la /newtest
total 12
drwxr-xr-x    2 root     root          4096 Aug 25 17:00 .
drwxr-xr-x    1 root     root          4096 Aug 25 17:00 ..
-rwxr-xr-x    1 root     root            30 Aug 25 17:00 secret_password.yaml

bash-5.1# checkov -f /newtest/secret_password.yaml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.371

bash-5.1#
```

**To Reproduce**
1. Create the files listed above with the same contents.
2. Mount the directory into checkov container
3. Perform `checkov -f` commands as per above

**Expected behavior**
I would expect to see:
```
bash-5.1# checkov -f /newtest/secret_password.yaml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.371

secrets scan results;
```
And the results of the findings.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Container: bridgecrew/checkov:2
 - Running on Ubuntu, which is running on Windows 10 WSL2
 - Checkov Version: 2.0.371

**Comment by vangundy-jason-pfg** [comment]
I think this is very similar / related to: https://github.com/bridgecrewio/checkov/issues/1580

**Comment by nimrodkor** [comment]
Was resolved by #1601 . Release version 2.0.407 (released in the following minutes) should set this straight. thanks for reporting @mtcolman !

**Comment by mtcolman** [comment]
@nimrodkor I've just tested this and I don't believe it's fixed.
```
bash-5.1# checkov -d ./

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.407

bash-5.1# pwd
/test
bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Aug 25 16:35 .
drwxr-xr-x    1 root     root          4096 Sep 12 16:17 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            44 Aug 25 16:34 providers.tf
-rwxrwxrwx    1 root     root            30 Aug 25 16:35 secret_password.yaml
bash-5.1# cat password.txt
password: mypassword
b64password: bXlwYXNzd29yZAo=
mypassword=secretkey
```

**Comment by mtcolman** [comment]
But again if I make the terraform directory I get:
```
bash-5.1# mkdir /terraform/aws/provider.tf
mkdir: can't create directory '/terraform/aws/provider.tf': No such file or directory
bash-5.1# mkdir -p /terraform/aws/
bash-5.1# vi /terraform/aws/providers.tf
bash-5.1# checkov -d /terraform/

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.407

terraform scan results:

Passed checks: 1, Failed checks: 0, Skipped checks: 0

Check: CKV_AWS_41: "Ensure no hard coded AWS access key and secret key exists in provider"
        PASSED for resource: aws.default
        File: /aws/providers.tf:1-10
        Guide: https://docs.bridgecrew.io/docs/bc_aws_secrets_5
```

**Comment by mtcolman** [comment]
It's still not finding secrets:
```
bash-5.1# pwd
/test
bash-5.1# checkov -d . --framework all

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.407

bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Aug 25 16:35 .
drwxr-xr-x    1 root     root          4096 Sep 12 16:29 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            44 Aug 25 16:34 providers.tf
-rwxrwxrwx    1 root     root            30 Aug 25 16:35 secret_password.yaml
bash-5.1# cat providers.tf
access_key = "sfffglfgjldfjdlrt5454002lfofd"
```

**Comment by mtcolman** [comment]
I've amended the password files and given this another go at versions `2.0.407` and `2.0.413`. It is now finding the AWS secret, but still failing to find the "Base64 High Entropy String" (as per https://docs.bridgecrew.io/docs/git_secrets_6):
```
bash-5.1# pwd
/test

bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Sep 14 09:32 .
drwxr-xr-x    1 root     root          4096 Sep 14 09:39 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            36 Sep 14 09:35 providers.tf
-rwxrwxrwx    1 root     root            76 Sep 14 09:39 secret_password.yaml
drwxrwxrwx    1 root     root          4096 Sep 14 09:32 terraform

bash-5.1# cat providers.tf
access_key = "AKIAAI0SF0DNN7EXAMPLE"

bash-5.1# cat secret_password.yaml
pwd: correcthorsebatterystaple
newpwd: Y29ycmVjdGhvcnNlYmF0dGVyeXN0YXBsZQ==

bash-5.1# checkov -d ./

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.413

secrets scan results:

Passed checks: 0, Failed checks: 2, Skipped checks: 0

Check: CKV_SECRET_2: "AWS Access Key"
        FAILED for resource: 2b4e50bcbde22261373a5e3cf6925a818837181a
        File: /providers.tf:1-2
        Guide: https://docs.bridgecrew.io/docs/git_secrets_2

                1 | access_key = "AKIAAI0SF0DNN7EXAMPLE"


Check: CKV_SECRET_2: "AWS Access Key"
        FAILED for resource: 2b4e50bcbde22261373a5e3cf6925a818837181a
        File: /terraform/aws/providers.tf:1-2
        Guide: https://docs.bridgecrew.io/docs/git_secrets_2

                1 | access_key = "AKIAAI0SF0DNN7EXAMPLE"
```

I can't see any difference between what I'm doing with `secret_password.yaml` and what was shown in the [blog](https://bridgecrew.io/blog/checkov-secrets-scanning-find-exposed-credentials-in-iac/).
