### ISSUE TITLE
no output returned?

### ISSUE THREAD

**Issue by caclifton** [bridgecrewio/checkov#220]
Using checkov v1.0.214, on some of our aws cloudformation files, no output is returned, is that expected?

e.g., 

checkov -f iam-infra.yaml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

version: 1.0.214

WTMZ-TMZ0096781:cloudformation xcclifto$

**Comment by schosterbarak** [comment]
hey @caclifton  do you mind sharing the cloudformation file?

**Comment by chrisheady81** [comment]
I'm seeing the same behavior. I think the -f switch is broken.

**Comment by schosterbarak** [comment]
-f file is now fixed: https://github.com/bridgecrewio/checkov/pull/228

**Comment by chrisheady81** [comment]
Nice!

**Comment by aliasfour** [comment]
Excellent!

**Comment by caclifton** [comment]
@schosterbarak using new version 1.0.249, still seeing no output from files that I emailed you ,

checkov -f static-infra.yaml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

version: 1.0.249

**Comment by schosterbarak** [comment]
Fixed! sent an email :)
